[package]
name = "who_asked"
version = "0.1.0"
edition = "2021"
authors = ["Nav <navaneeth.sajiv@gmail.com>"]
description = "Who tf asked bro?"

[dependencies]
actix-files = "0.6.2"
actix-web = "4.2.1"
rand = "0.8.5"

[profile.release]
lto = true
opt-level = 3
